%% Allow server client to publish everywhere
{allow, {user, "server"}, publish, ["#"]}.

%% Allow clients to subscribe to any topic
{allow, {ipaddr, "0.0.0.0/0"}, subscribe, ["signals/#", "comments/#", "profiles/#", "notifications/#"]}.

%% Deny clients from publishing
{deny, all, publish, ["#"]}.

%% Allow all else
{allow, all}.
